version: 1.0.{build}

skip_tags: true

branches:
  only:
    - master

before_build:
  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - mkdir "%APPVEYOR_BUILD_FOLDER%\binaries"
  - ps: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.3-msvc.zip -OutFile libsodium.zip
  - 7z x "%APPVEYOR_BUILD_FOLDER%\libsodium.zip" -o"%APPVEYOR_BUILD_FOLDER%\libsodium"
  - cd "build"
  - cmake.exe -G "Visual Studio 12" .. -DWITH_SODIUM=ON -DSODIUM_ROOT_DIR="%APPVEYOR_BUILD_FOLDER%\libsodium" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/binaries" -DBUILD_TESTING=OFF

build_script:
  - cmake.exe --build "%APPVEYOR_BUILD_FOLDER%\build" --target install --config Release
  - cp "%APPVEYOR_BUILD_FOLDER%\libsodium\Win32\Release\v120\dynamic\libsodium.dll" "%APPVEYOR_BUILD_FOLDER\binaries\bin\"
  - 7z a libzmq4.zip "%APPVEYOR_BUILD_FOLDER%\binaries\*"
  - appveyor PushArtifact libzmq4.zip

artifacts:
  - path: libzmq4.zip
    name: libzmq4

deploy:
  release: libzmq4x-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: XGGnX5AXrVFxrS2Z2tbByWR+pA+ExMjZZmCyMqb7rPFEgSJjUF6PuYFl6M5uzl1r 
  artifact: libzmq4.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
